CREATE TABLE t_user
(
    USER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(128) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    NICK_NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    ROLE VARCHAR(128) NOT NULL,
    ACCOUNT_NON_EXPIRED TINYINT DEFAULT 1 NOT NULL,
    ACCOUNT_NON_LOCKED TINYINT DEFAULT 1 NOT NULL,
    CREDENTIALS_NON_EXPIRED TINYINT DEFAULT 1 NOT NULL,
    ENABLED TINYINT DEFAULT 1 NOT NULL
);
CREATE UNIQUE INDEX unique_EMAIL ON t_user (EMAIL);
CREATE UNIQUE INDEX unique_NICK_NAME ON t_user (NICK_NAME);
CREATE UNIQUE INDEX unique_USER_ID ON t_user (USER_ID);
CREATE UNIQUE INDEX unique_USER_NAME ON t_user (USER_NAME);
